spring:
  application: 
    name: "storemanager"
    comment: >
      "upgrade a la versión 2, ya incluye base de datos"
      "integración de servicios"
      "initial deploy"
    comments2:
      - "item1"
      - "item2"
    buildtime: "@buildtime@"
    version: "@project.version@"
  profiles: 
    active: "@spring.profiles.active@"
    default: "@spring.profiles.active@"
  thymeleaf:
    check-template-location: true
    cache: false
server:
  servlet:
    contextPath: /storemanager
  port: 8888
logging:
  level:
    .: debug
    org:
      hibernate: DEBUG
      hibernate.type: DEBUG
      springframework: DEBUG
    mx.devhive: DEBUG
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://user:pass@mongoameliecluster-bx74j.azure.mongodb.net/test
      authentication-database: "store"
      database: "store"

  
 